Quizzit/urls.py
from django.contrib import admin
from django.urls import path, include
from quizzit_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('quizzit/', include('quizzit_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizzit_app/urls.py
from django.urls import path
from quizzit_app import views

app_name = 'quizzit'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('categories/', views.categories, name='categories'),
    path('categories/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('<slug:category_name_slug>/<slug:quiz_name_slug>/', views.quiz, name='quiz'),
    path('howtoplay/', views.howtoplay,name='howtoplay'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('leaderboards/', views.leaderboards, name='leaderboards'),
]

templates/quizzit/about.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %} 

{% block body_block %}
    <div style="font-family: 'Trebuchet MS'; text-align: center">
        <h1><u>About</u></h1>
        <p style="font-size: 22px">
            Quizzit is a web application which delivers quizzes to people who want to challenge themselves 
            on specific topics and categories against the world. <br />
            The website is easy to navigate through, you can easily create an account using the Sign Up button or simply play quizzes as a guest.
            <div>
                <h2><u>Account Privileges</u></h2>
                <p style="font-size: 21px">
                    All types of users will be able to play multiple choice quizzes from all genres in the easy to medium difficulty categories. 
                    Registered users will be able to play the hard difficulty and will be able to access more features in the application. 
                    Users will be able to view a leader-board, (only listing registered users) where they can see if their attempt was excellent, adequate or worse in comparison to other users. 
                    This will be based off the number of correct answers and time remaining for each quiz the user attempts. This adds a competitive edge making it an increasingly challenging and fun concept of doing quizzes. 
                </p>
            </div>
        </p>
        <br />
        <h2><u>Contact Us</u></h2>
        <div style="font-size: 21px">
        <p>
            Feel free to contact us by e-mail if you have queries about our site. <br />
            <ul style="list-style-position: inside">
                <li>Ashwyn Bahanda: 2457696B@student.gla.ac.uk</li>
                <li>Stergious Aji: 2546916A@student.gla.ac.uk</li>
                <li>Eric Choy: 2465059c@student.gla.ac.uk</li>
                <li>Kai Cheong: 2512290c@student.gla.ac.uk</li>
            </ul>
        </p>
        </div>
    </div>
{% endblock %}

templates/quizzit/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <title>
        Quizzit - 
        {% block title_block %}
            Home
        {% endblock %} 
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    {% block link_block %}
    {% endblock %}
</head>

<body>
    <!--HEADER AND NAVIGATION BAR-->
    <div class="header">
        <div id="logo-container">
            <a href="{% url 'quizzit:home' %}">
                <img id="header-logo" src="{% static 'images/Quizzit_Logo.png' %}" alt="Quizzit-Logo-Header">
            </a>
        </div>
        <div id="center-content">
            <input id="search-box" type="text" placeholder="Search">
            <button id="btnSearch" type="submit"><i class="fa fa-search"></i></button>
        </div>
        <div id="right-content">
            {% if user.is_authenticated %}
            <a href="{% url 'quizzit:logout' %}">
                <button class="right-buttons" id="btnLogin">Log out</button>
            </a>
                
            
            {% else %}
            <a href="{% url 'quizzit:register' %}">
                <button class="right-buttons" id="btnSignUp">Sign Up</button>
            </a>
            <a href="{% url 'quizzit:login' %}">
                <button class="right-buttons" id="btnLogin">Log in</button>
            </a>
                
            {% endif %}
        </div>
    </div>

    
    <div class="navbar">
        <div class="dropdown">
            <a id="categories" href="{% url 'quizzit:categories' %}">Categories</a>
            <div class="dropdown-categories">
                {% for c in categories %}
                    <a href="{% url 'quizzit:show_category' c.slug %}">{{ c.name }}</a>
                {% endfor %}
                <!-- <a href="#history">History</a>
                <a href="#geography">Geography</a>
                <a href="#sport">Sport</a>
                <a href="#sport">Mathematics</a>
                <a href="#sport">Biology</a>
                <a href="#sport">Business</a>
                <a href="#sport">Physics</a>
                <a href="#sport">Movies</a>
                <a href="#sport">Tv Shows</a>
                <a href="#sport">Chemistry</a> -->
            </div>
        </div>
        <a href="{% url 'quizzit:howtoplay' %}">How to Play</a>
        <a href="{% url 'quizzit:leaderboards' %}">Leaderboard</a>
        <a href="{% url 'quizzit:about' %}">About</a>
    </div>


    <div id='content-div'>
        {% block body_block %}
        {% endblock %}
    </div>

    
    <script src="{% static 'js/jquery-3.6.0.min.js' %}" type="text/javascript"></script>
    {% block extra_script %}
    {% endblock %}

</body>
</html>

templates/quizzit/categories.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Categories
{% endblock %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/categories.css' %}"/>
{% endblock %}

{% block body_block %}
    <h1><u>Categories</u></h1>
    <div class="categories-container">
        {% if categories %}
            {% for c in categories %}
                <a href="{% url 'quizzit:show_category' c.slug %}">
                    <div class="container">
                        <div class ="card">
                                <div class="difficulty">
                                    <h2>{{ c.name }}</h2>
                                    <div class="level">
                                        <span>Easy</span>
                                        <span>Med</span>
                                        <span>Hard</span>
                                    </div>
                                </div>
                                </div>
<!--                    <button class="buttons">{{ c.name }}</button></a>-->
                        
            {% endfor %}
        {% else %}
            <h1>There are no categories to show.</h1>
        {% endif %}
    </div>
{% endblock %}

templates/quizzit/category.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/category.css' %}"/>
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <div class="buttons-container">
            {% for q in quiz %}
                {% if q.difficulty == q.EASY %}
                    <a href="{% url 'quizzit:quiz' category.slug q.slug %}"><button id="btnEasy">Easy</button></a>
                {% elif q.difficulty == q.MED %}
                    <a href="{% url 'quizzit:quiz' category.slug q.slug %}"><button id="btnMedium">Medium</button></a>
                {% elif q.difficulty == q.HARD %}
                    <a href="{% url 'quizzit:quiz' category.slug q.slug %}"><button id="btnHard">Hard</button></a>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/quizzit/home.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block body_block %}
    <div class='Logo-image'>
        <img id="center-logo" src="{% static 'images/Quizzit_Logo.png' %}" alt="Quizzit-Logo">
    </div>

    <div class="slideshow-container">

        <div class="mySlides fade">
            <div class="rectangles" id="rectangle1">
                <h1 id="title">Top Three Most Popular Quizzes:</h1>
                <a class="quiz_links" href="{% url 'quizzit:quiz' most_popular_quiz_1.category.slug most_popular_quiz_1.slug %}">
                    <button id="quiz_1" class="quiz_buttons">{{ most_popular_quiz_1.name }}</button>
                </a>
            </div>
        </div>

        <div class="mySlides fade">
            <div class="rectangles" id="rectangle2">
                <h1 id="title">Top Three Most Popular Quizzes:</h1>
                <a class="quiz_links" href="{% url 'quizzit:quiz' most_popular_quiz_2.category.slug most_popular_quiz_2.slug %}">
                    <button id="quiz_2" class="quiz_buttons">{{ most_popular_quiz_2.name }}</button>
                </a>
            </div>
        </div>

        <div class="mySlides fade">
            <div class="rectangles" id="rectangle3">
                <h1 id="title">Top Three Most Popular Quizzes:</h1>
                <a class="quiz_links" href="{% url 'quizzit:quiz' most_popular_quiz_3.category.slug most_popular_quiz_3.slug %}">
                    <button id="quiz_3" class="quiz_buttons">{{ most_popular_quiz_3.name }}</button>
                </a>
            </div>
        </div>

        </div>
        <br>

        <div style="text-align:center">
          <span class="dot"></span> 
          <span class="dot"></span> 
          <span class="dot"></span> 
        </div>

        <script>
        var slideIndex = 0;
        showSlides();
        
        function showSlides() {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";  
            }
            slideIndex++;
            if (slideIndex > slides.length) {slideIndex = 1}    
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex-1].style.display = "block";  
            dots[slideIndex-1].className += " active";
            setTimeout(showSlides, 5000); 
        }
        </script>
    </div>
{% endblock %}

templates/quizzit/howtoplay.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block title_block %}
    How To Play
{% endblock %}


{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/howtoplay.css' %}"/>
{% endblock %}

{% block body_block %}
    <div style="font-family: 'Trebuchet MS'; text-align: center">
        <h1><u>How To Play</u></h1>
        <p style= "font-size: 22px">
            All users will be able to play a quiz. Just head to the Categories section and pick your quiz. <br/><br/>
            Each user will have a set time to play and complete a quiz. For unregistered users, the hardened difficult is locked. As well as this, your scores will not be added to the leaderboards, so register! <br/><br/>
            You will be able to see how well you did compared to others after completing the quiz. <br/><br/>
            Once you complete or attempt a quiz, you will not be able to play that quiz for another 24 hours.
        </p>
    </div>          
{% endblock %}

templates/quizzit/leaderboards.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/leaderboards.css' %}"/>
{% endblock %}

{% block body_block %}
    
    <h1>Category</h1>
    <div class="leaderboards">
        <div id="ldEasy">
            <h1>EASY</h1>
            <table class="scroll">
                <thead>
                <tr>
                    <th scope="col" colspan="1">Rank</th>
                    <th scope="col" colspan="1">Username</th>
                    <th scope="col" colspan="1">Score</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Siva</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Raman</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Sivaraman</td>
                    <td>50</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div id="ldMedium">
            <h1>MEDIUM</h1>
            <table class="scroll">
                <thead>
                <tr>
                    <th scope="col" colspan="1">Rank</th>
                    <th scope="col" colspan="1">Username</th>
                    <th scope="col" colspan="1">Score</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Siva</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Raman</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Sivaraman</td>
                    <td>50</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div id="ldHard">
            <h1>HARD</h1>
            <table class="scroll">
                <thead>
                <tr>
                    <th scope="col" colspan="1">Rank</th>
                    <th scope="col" colspan="1">Username</th>
                    <th scope="col" colspan="1">Score</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1</td>
                    <td>Siva</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Raman</td>
                    <td>50</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Sivaraman</td>
                    <td>50</td>
                </tr>
                </tbody>
            </table>
        </div>
        
    </div>
    <div class="leaderboard_buttons">
        <a class="previous" onclick="history.back(-1)">&#8249; Previous</a>
        <p>1/10</p>
        <a class="next">Next &#8250;</a>
    </div>

{% endblock %}

templates/quizzit/login.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
{% endblock %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <!-- <h1>Login</h1>
    <form id="login_form" method="post" action="{% url 'quizzit:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form> -->

    {% if invalid_login %}
        <h1 class="invalid">INVALID LOGIN</h1>
    {% else %}
        <form id="login_form" method="post" action="{% url 'quizzit:login' %}">
            {% csrf_token %}
            <div class="container">
              <h1>Login</h1>
              <hr>
            
              <label for="username"><b>Username</b></label>
              <input type="text" placeholder="Enter Username" name="username" id="txtUsername" required>
            </br>
            
              <label for="password"><b>Password</b></label>
              <input type="password" placeholder="Enter Password" name="password" id="txtPassword" required>

              <button type="submit" class="btnLogin">Login</button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/quizzit/quiz.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/circular timer.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz.css' %}"/>
{% endblock %}

{% block title_block %}
    {% if quiz %}
        {{ quiz.name }}
    {% else %}
        Unknown Quiz
    {% endif %}
{% endblock %}

{% block body_block %}

    {% if finished %}
        <h1>Result</h1> 
            
        {% for que, ans in ques_and_anss%}  
            {% if que.answer == ans %}
                {% firstof 'question-correct' as class_name %}
                {% firstof question_score as score_var %}
            {% else %}
                {% firstof 'question-wrong' as class_name %}
                {% firstof '0' as score_var %}
            {% endif %}

            <div class='{{ class_name }}'>
                <p>Q{{que.index}}: {{que.question_text}}</p>
                
                <ul class="question-row2">
                    <li class="flex-item">Correct Answer: {{que.answer}}</li>
                    <li class="flex-item">Your Answer: {{ans}}</li>
                    <li class="flex-item">Score: {{ score_var }} </li>
                </ul>
            </div>    
        {% endfor %}

        <div class='result-bottom'>
            <p style='text-align: left; font-size: 20px;'>Time Remaining: {{ formatted_time }}</p>
            <p class='rounded-border'>Total Score: {{ score }}</p>
            <a class='finish button-base-style' href="{% url 'quizzit:home' %}">Home</a>
        </div>
        

    {% else %}

        <div id="timer" data-start-time="{{ start_time }}"></div>

        <div class="question-container">
            <h1 id="txtQuestion">Q{{ question.index }}: {{ question.question_text }}</h1>
        </div>

        <div class="multiple-choice-container">
            <button class="mc-buttons" id="btnChoiceA" data-choice="A">{{ question.choiceA }}</button>
            <button class="mc-buttons" id="btnChoiceB" data-choice="B">{{ question.choiceB }}</button>
        </div>
        <div class="multiple-choice-container">
            <button class="mc-buttons" id="btnChoiceC" data-choice="C">{{ question.choiceC }}</button>
            <button class="mc-buttons" id="btnChoiceD" data-choice="D">{{ question.choiceD }}</button>
        </div>

        <div class="control-question-container">
            {% csrf_token %}

            <div></div>

            <p><span id="index-indicator">{{ question.index }}</span>/{{ num_of_questions }}</p>

            <button class="next button-base-style" id="next-btn">Next &#8250;</button>

            <button class="finish button-base-style" id="finish-btn" style="display: none">Finish</button>
        </div>

    {% endif %}

{% endblock %}


{% block extra_script %}
    <script type="text/javascript" src="{% static 'js/circular timer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/quiz.js' %}"></script>
{% endblock %}

templates/quizzit/register.html
{% extends 'quizzit/base.html' %}
{% load staticfiles %}

{% block link_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
{% endblock %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    {% if registered %}
        <h1><strong>Thank you for registering!</strong></h1>
        <button id="btnHome">Return to Home</button>
    {% else %}
        <div class="register-fields">
            <h1><u>Register</u></h1>
            <br />
            <form id="user_form" method="post" action="{% url 'quizzit:register' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input id="btnRegister" type="submit" name="submit" value="Register" />
            </form>
        </div>
    {% endif %}
{% endblock %}